### ISSUE TITLE
check.__getattr__ hangs when requested item missing from Pingdom response

### ISSUE THREAD

**Issue by aaronfay** [KennethWilke/PingdomLib#15]
I think that `Check.__getattr__` is in a loop of some kind when I try to access `lasterrortime` attribute on a check where it doesn't exist: 

```
In [1]: details = check.getDetails()
In [2]: details
Out[2]:
{u'contactids': [10919360, 10919362, 10919361],
 u'created': 1419369381,
 u'hostname': u'domainhasbeenchanged.com',
 u'id': 1461209,
 u'lastresponsetime': 630,
 u'lasttesttime': 1421273340,
 u'name': u'domainhasbeenchanged.com',
 u'notifyagainevery': 3,
 u'notifywhenbackup': True,
 u'resolution': 1,
 u'sendnotificationwhendown': 4,
 u'sendtoandroid': False,
 u'sendtoemail': True,
 u'sendtoiphone': False,
 u'sendtosms': False,
 u'sendtotwitter': False,
 u'status': u'up',
 u'tags': [],
 u'type': {u'http': {u'encryption': False,
   u'port': 80,
   u'requestheaders': {u'User-Agent': u'Pingdom.com_bot_version_1.4_(http://www.pingdom.com)'},
   u'url': u'/'}},
 u'use_legacy_notifications': True}
In [3]: 'lasterrortime' in details
Out[3]: False
In [4]: hasattr(check, 'lasterrortime')
<hangs here>
```

After about 30 seconds it finally returns with a `False` value. A quick at the code shows that `__getattr__` calls `getattr` again internally, so I suspect a loop or something, but I haven't tested it.

**Comment by gwillem** [comment]
Same for ```contactids```. It wasn't added as a field here https://github.com/KennethWilke/PingdomLib/blob/d1bf0d51a6b2137650793917bd283000f20abaef/pingdomlib/check.py#L50 and now I understand why. If there are contacts assigend yet, the API doesn't return this field at all. But ```__getattr__``` assumes it is.

**Comment by KennethWilke** [comment]
It looks like this is fixed with the recent merges and now up as v1.9. @aaronfay  @gwillem is this corrected to your satisfaction?

**Comment by aaronfay** [comment]
This has been tested for my purposes at 1.9:

```
(Pdb) for check in checks: print check.getDetails().get('lasterrortime')
1422329382
1421322488
1421086726
1422329448
1422329291
1422233454
1421317053
1422561299
1422329521
1422329511
None
1422329514
None
1422329526
1422329558
1422329501
1422329532
1422329474
1421316918
1422329295
1421082263
1422329458
1422329486
1421317047
None
1421716993
1422329519
1421316279
1422329502
```

Thanks!

**Comment by KennethWilke** [comment]
Awesome! Thanks for getting that fixed, will close this issue out
