### ISSUE TITLE
wsgiref dependency doesn't work on Python 3

### ISSUE THREAD

**Issue by haxoza** [KennethWilke/PingdomLib#25]
Hi Kenneth! I'm trying to install PingdomLib on Python 3 but with no luck because of `wsgiref` dependency. As far as I know [it is built-in to Python 3](https://docs.python.org/3/library/wsgiref.html).

Couldn't you just remove this dependency from `setup.py`? Is it somehow used by your library? I can't see any direct usages in the source code.

**Comment by KennethWilke** [comment]
Howdy @haxoza, sorry for the late response on this, I believe pip freeze tossed that in there because of something related to requests and it should be fine without it. I'll get that dropped and put out a new release today.

**Comment by haxoza** [comment]
Thanks!
